name: CI

on:
  push:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: 安装 node 14.10
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14.10'
      - name: 将代码检出
        uses: actions/checkout@v2
      - name: 安装依赖并且开始打包
        run: npm install && npm run make
      - name: 添加 artifact
        uses: actions/upload-artifact@v2
        with:
          name: oss-client-win-release
          path: out/make/squirrel.windows/x64/
  build-mac:
    runs-on: macOS-latest
    steps:
      - name: 安装 node 14.10
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14.10'
      - name: 将代码检出
        uses: actions/checkout@v2
      - name: 安装依赖并且开始打包
        run: npm install && npm run make
      - name: 添加 artifact
        uses: actions/upload-artifact@v2
        with:
          name: oss-client-mac-release
          path: out/make/zip/darwin/x64/
